import "./globals.css"

import { Inter } from "next/font/google"

import { cn } from "@/lib/utils"
// import localFont from 'next/font/local';
import { Toaster } from "@/components/ui/toaster"
import { TailwindIndicator } from "@/components/tailwind-indicator"

const fontSans = Inter({ subsets: ["latin"], variable: "--font-sans" })

// const fontHeading = localFont({
//   src: '../assets/fonts/CalSans-SemiBold.woff2',
//   variable: '--font-heading',
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
          // fontHeading.variable
        )}
      >
        {/* <ThemeProvider attribute='class' defaultTheme='system' enableSystem> */}
        {children}
        {/* <Analytics /> */}
        <Toaster />
        <TailwindIndicator />
        {/* </ThemeProvider> */}
      </body>
    </html>
  )
}
